import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useSimulation } from '../../hooks/useSimulation';
import { Play, Pause, RotateCcw, Layers, Sliders } from 'lucide-react';
export const ControlPanel = () => {
    const { isPlaying, timeScale, hypocenter, isMeshVisible, play, pause, reset, setDepth, setMagnitude, setTimeScale, toggleMeshVisible } = useSimulation();
    return (_jsxs("div", { className: "glass-panel absolute bottom-6 right-6 z-40 p-5 rounded-2xl w-72 text-white space-y-4 shadow-2xl pointer-events-auto", children: [_jsxs("div", { className: "flex items-center justify-between border-b border-slate-700/60 pb-3", children: [_jsxs("div", { className: "flex items-center space-x-2 font-bold text-base text-cyan-400 text-glow-cyan", children: [_jsx(Sliders, { className: "w-5 h-5" }), _jsx("span", { children: "\u30B7\u30DF\u30E5\u30EC\u30FC\u30B7\u30E7\u30F3\u5236\u5FA1" })] }), _jsxs("button", { onClick: toggleMeshVisible, className: `flex items-center space-x-1 text-xs px-2.5 py-1.5 rounded-lg border transition-all ${isMeshVisible
                            ? 'bg-cyan-600/80 border-cyan-400 text-white shadow-lg'
                            : 'bg-slate-800/60 border-slate-600 text-slate-300 hover:bg-slate-700'}`, title: "\u63A8\u8A08\u9707\u5EA6\u5206\u5E03\u56F3 (250m\u30E1\u30C3\u30B7\u30E5) \u306E\u8868\u793A\u5207\u308A\u66FF\u3048", children: [_jsx(Layers, { className: "w-3.5 h-3.5" }), _jsx("span", { children: "\u63A8\u8A08\u9707\u5EA6" })] })] }), _jsxs("div", { className: "flex items-center justify-between space-x-2", children: [!isPlaying ? (_jsxs("button", { onClick: play, className: "premium-btn flex-1 bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-white py-2.5 px-4 rounded-xl font-semibold flex items-center justify-center space-x-2 shadow-lg shadow-cyan-500/20 transition-all", children: [_jsx(Play, { className: "w-5 h-5 fill-current" }), _jsx("span", { children: "\u518D\u751F" })] })) : (_jsxs("button", { onClick: pause, className: "premium-btn flex-1 bg-gradient-to-r from-amber-500 to-orange-600 hover:from-amber-400 hover:to-orange-500 text-white py-2.5 px-4 rounded-xl font-semibold flex items-center justify-center space-x-2 shadow-lg shadow-orange-500/20 transition-all", children: [_jsx(Pause, { className: "w-5 h-5 fill-current" }), _jsx("span", { children: "\u4E00\u6642\u505C\u6B62" })] })), _jsx("button", { onClick: reset, className: "premium-btn bg-slate-800/80 hover:bg-slate-700 text-slate-300 p-2.5 rounded-xl border border-slate-600 shadow-md hover:shadow-slate-500/20 transition-all", title: "\u30EA\u30BB\u30C3\u30C8", children: _jsx(RotateCcw, { className: "w-5 h-5" }) })] }), _jsxs("div", { className: "space-y-1.5", children: [_jsx("label", { className: "text-xs text-slate-400 font-medium", children: "\u518D\u751F\u901F\u5EA6:" }), _jsx("div", { className: "grid grid-cols-4 gap-1.5", children: [1, 2, 5, 10].map((speed) => (_jsxs("button", { onClick: () => setTimeScale(speed), className: `py-1 text-xs font-semibold rounded-lg transition-all ${timeScale === speed
                                ? 'bg-cyan-500 text-slate-950 font-bold shadow'
                                : 'bg-slate-800/60 text-slate-300 hover:bg-slate-700'}`, children: [speed, "x"] }, speed))) })] }), _jsxs("div", { className: "space-y-1.5 pt-2 border-t border-slate-700/60", children: [_jsxs("div", { className: "flex justify-between text-xs", children: [_jsx("span", { className: "text-slate-400 font-medium", children: "\u9707\u6E90\u306E\u6DF1\u3055 (Depth):" }), _jsxs("span", { className: "font-semibold text-cyan-300 text-glow-cyan", children: [hypocenter.depth, " km"] })] }), _jsx("input", { type: "range", min: "0", max: "700", step: "5", value: hypocenter.depth, onChange: (e) => setDepth(parseFloat(e.target.value)), className: "w-full accent-cyan-400 bg-slate-800 h-1.5 rounded-lg cursor-pointer" })] }), _jsxs("div", { className: "space-y-1.5", children: [_jsxs("div", { className: "flex justify-between text-xs", children: [_jsx("span", { className: "text-slate-400 font-medium", children: "\u30DE\u30B0\u30CB\u30C1\u30E5\u30FC\u30C9 (Mw):" }), _jsxs("span", { className: "font-semibold text-rose-400 text-glow-rose", children: ["M ", hypocenter.magnitude.toFixed(1)] })] }), _jsx("input", { type: "range", min: "2.0", max: "13.0", step: "0.1", value: hypocenter.magnitude, onChange: (e) => setMagnitude(parseFloat(e.target.value)), className: "w-full accent-rose-500 bg-slate-800 h-1.5 rounded-lg cursor-pointer" })] })] }));
};
